baseURL = "https://hexbee-blog.netlify.app"
disablePathToLower = true
disqusShortname = ""
googleAnalytics = ""
hasCJKLanguage = true
languageCode = "zh-CN"
preserveTaxonomyNames = true
summaryLength = 140
theme = "maupassant"
title = "Hexbee的博客"
[author]
name = "Hexbee"
[markup.highlight]
lineNos = true
style = "github"
[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 3
[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 2
[[menu.main]]
identifier = "tools"
name = "工具"
url = "/tools/"
weight = 1
[params]
author = "Hexbee"
beian = "XXXXXXX号"
busuanzi = true
customCSS = ["douban.css", "other.css"]
customJS = ["douban.js"]
description = "专注于IT互联网"
fancybox = true
googleAd = ""
keywords = "Golang,Python,C++,Rust,Shell,Git"
localSearch = true
subtitle = "专注于IT互联网，包括但不限于Python/Go/C++/Rust/数据可视化等"
toc = true
[params.cc]
link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
[params.utteranc]
enable = true
issueTerm = "pathname"
repo = "hexbee/hugo-maupassant-forestry"
theme = "github-light"
[[params.links]]
name = "飞雪无情的博客"
title = "飞雪无情的博客"
url = "https://www.flysnow.org/"
